services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
